name: Scrape and Rank

on:
  workflow_dispatch:

jobs:
  scrape:
    name: Scrape 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3 
        with:
          node-version: 'latest'

      - name: Install Packages
        run: |
          yarn install
     
      - name: Scrape Results
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: |
          yarn scrape
  
  rank:
    name: Rank the results
    runs-on: ubuntu-latest
    needs: scrape
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3 
        with:
          node-version: 'latest'
      
      - name: Install Packages
        run: |
          yarn install
      
      - name: Scrape Results
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: |
          yarn rank
